Name: Rocket.Surgery.Extensions.Configuration
NuGet: Rocket.Surgery.Extensions.Configuration
Assemblies:
- "/**/Rocket.Surgery.Extensions.Configuration.dll"
Repository: https://github.com/RocketSurgeonsGuild/Microsoft.Extensions
Author: Rocket Surgeons
Description: "TODO"
Categories:
- Cake
